abstract: Perl extension to OpenSSL's X509 API.
author: 'Dan Sully, <daniel@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Crypt-OpenSSL-X509
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
version: 0.4
